### PR TITLE
Updates get_client_secrets.rst to match the latest UI.

### PR DESCRIPTION
**Pull request by mbookman**
Also the instructions concluded with downloading the client_secrets.json-
it should just focus on getting the client id and secret.
If we need another version that involves downloading the file, we
should create a get_client_secrets_json.rst.

### CODE REVIEW

**Comment by deflaux** [comment]
In the other places where this is included, the file is needed.  This would break those other flows (e.g., use_cases/run_picard_and_gatk/index.rst).

**Comment by mbookman** [comment]
I had looked and that file no longer references this one.

**Comment by mbookman** [comment]
Thank-you. I did not find that as there was an include of an include.
I will fix the instructions for getting the client_secrets.json, since they are now out of date.
I'll create a parallel "get_client_secrets_json.rst" and update collapsible_get_client_secrets.rst and genomics_tools_setup.rst.

**Comment by deflaux** [comment]
LGTM

**Pull request merged**
